# -*- coding: utf-8 -*-
"""part1_grade_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pIogjAc51DpGhcjoToH5C5omoCpGh3IB
"""

# ============================================================
# Assignment Part 1: Python Basics & Control Flow
# Theme: Student Grade Tracker
# ==============================================================
# TASK 1 — Data Parsing & Profile Cleaning
# ==============================================================


raw_students = [
    {"name": "  ayesha SHARMA  ", "roll": "101", "marks_str": "88, 72, 95, 60, 78"},
    {"name": "ROHIT verma",       "roll": "102", "marks_str": "55, 68, 49, 72, 61"},
    {"name": "  Priya Nair  ",    "roll": "103", "marks_str": "91, 85, 88, 94, 79"},
    {"name": "karan MEHTA",       "roll": "104", "marks_str": "40, 55, 38, 62, 50"},
    {"name": " Sneha pillai ",    "roll": "105", "marks_str": "75, 80, 70, 68, 85"},
]

cleaned_students = []

print("*" * 40)
print("TASK 1 — Data Parsing & Profile Cleaning")
print("*" * 40)

for student in raw_students:

    # Cleaning the name formating
    clean_name = student["name"].strip().title()

    # Converting roll number from string to integer
    clean_roll = int(student["roll"])

    # Converting marks string to a list of integers
    clean_marks = [int(m) for m in student["marks_str"].split(", ")]

    # Validating the name
    # .isalpha() returns True if ALL characters in a string are letters
    # all([...]) returns True only if EVERY item in the list is True
    words = clean_name.split()
    name_is_valid = all(word.isalpha() for word in words)

    # Print valid/invalid message next to each student
    if name_is_valid:
        validity_msg = "✓ Valid name"
    else:
        validity_msg = "✗ Invalid name"

    # Build a new cleaned student dictionary and add it to our list
    cleaned = {
        "name":  clean_name,
        "roll":  clean_roll,
        "marks": clean_marks
    }
    cleaned_students.append(cleaned)

    # Printing the profile card
    print(f"\n================================")
    print(f"Student : {cleaned['name']}    {validity_msg}")
    print(f"Roll No : {cleaned['roll']}")
    print(f"Marks   : {cleaned['marks']}")
    print(f"================================")

# Print name in ALL CAPS for roll number 103
print("\n--- Special case for Roll No 103 ---")
for student in cleaned_students:
    if student["roll"] == 103:
        print(f"{student['name'].upper()}")

# ==============================================================
# TASK 2 — Marks Analysis Using Loops & Conditionals
# ==============================================================

print("\n" + "*" * 40)
print("TASK 2 — Marks Analysis Using Loops & Conditionals")
print("*" * 40)

student_name = "Ayesha Sharma"
subjects     = ["Math", "Physics", "CS", "English", "Chemistry"]
marks        = [88, 72, 95, 60, 78]

# Printing each subject with its grade
print(f"\nGrade report for {student_name}:")
print("-" * 35)

for subject, mark in zip(subjects, marks):
    if mark >= 90:
        grade = "A+"
    elif mark >= 80:
        grade = "A"
    elif mark >= 70:
        grade = "B"
    elif mark >= 60:
        grade = "C"
    else:
        grade = "F"

    # f-string with alignment: :<15 means left-align in 15 characters, :>3 right-align in 3
    print(f"  {subject:<12} | Marks: {mark:>3} | Grade: {grade}")

# Calculating statistics
total   = sum(marks)
average = round(total / len(marks), 2)
highest_mark = max(marks)
highest_idx  = marks.index(highest_mark)
highest_subj = subjects[highest_idx]
lowest_mark  = min(marks)
lowest_idx   = marks.index(lowest_mark)
lowest_subj  = subjects[lowest_idx]

print(f"\nTotal Marks    : {total}")
print(f"Average Marks  : {average}")
print(f"Highest Subject: {highest_subj} ({highest_mark})")
print(f"Lowest Subject : {lowest_subj} ({lowest_mark})")

# Simulate a marks-entry system

print("\n--- Add New Subjects (type 'done' to stop) ---")
new_count = 0  # counter for how many valid new subjects were added

while True:  # True means loop forever, using 'break' to stop it
    # Ask the user to type a subject name
    new_subject = input("Enter subject name (or 'done' to finish): ").strip()
    if new_subject.lower() == "done":
        break
    marks_input = input(f"Enter marks for {new_subject} (0-100): ").strip()
 # Managing Invalid input
    try:
        new_mark = int(marks_input)

        if 0 <= new_mark <= 100:
            subjects.append(new_subject)
            marks.append(new_mark)
            new_count += 1
            print(f"  ✓ Added {new_subject}: {new_mark}")
        else:
            print(f"  do not crash, and do not add invalid entries to the list. '{new_mark}' ignored.")

    except ValueError:
        print(f"  ⚠ Warning: '{marks_input}' do not crash, and do not add invalid entries to the list. Ignored.")

updated_total   = sum(marks)
updated_average = round(updated_total / len(marks), 2)
print(f"\n{new_count} new subject(s) added.")
print(f"Updated average across all subjects: {updated_average}")

# ==============================================================
# TASK 3 — Class Performance Summary
# ==============================================================

print("\n" + "*" * 40)
print("TASK 3 — Class Performance Summary")
print("*" * 40)

class_data = [
    ("Ayesha Sharma",  [88, 72, 95, 60, 78]),
    ("Rohit Verma",    [55, 68, 49, 72, 61]),
    ("Priya Nair",     [91, 85, 88, 94, 79]),
    ("Karan Mehta",    [40, 55, 38, 62, 50]),
    ("Sneha Pillai",   [75, 80, 70, 68, 85]),
]

print(f"\n{'Name':<18} | {'Average':^7} | {'Status'}")
print("-" * 42)

all_averages = []

for name, student_marks in class_data:
    avg = round(sum(student_marks) / len(student_marks), 2)
    all_averages.append(avg)


    status = "Pass" if avg >= 60 else "Fail"


    print(f"{name:<18} | {avg:^7} | {status}")

# Summary after the table
passed_count = sum(1 for avg in all_averages if avg >= 60)  # count averages >= 60
failed_count = len(all_averages) - passed_count

# Find topper
max_avg       = max(all_averages)
topper_idx    = all_averages.index(max_avg)
topper_name   = class_data[topper_idx][0]  # [0] gets the name from the tuple

# Class average
class_average = round(sum(all_averages) / len(all_averages), 2)

print(f"\nStudents Passed : {passed_count}")
print(f"Students Failed : {failed_count}")
print(f"Class Topper    : {topper_name} (Average: {max_avg})")
print(f"Class Average   : {class_average}")

# TASK 4 — String Manipulation Utility
# ==============================================================

print("\n" + "*" * 40)
print("TASK 4 — String Manipulation Utility")
print("*" * 40)

essay = "  python is a versatile language. it supports object oriented, functional, and procedural programming. python is widely used in data science and machine learning.  "

# Strip whitespace
clean_essay = essay.strip()
print(f"\nStep 1 — Stripped:\n{clean_essay}")

# Title Case
print(f"\nStep 2 — Title Case:\n{clean_essay.title()}")

# Count occurrences of "python"
python_count = clean_essay.count("python")
print(f"\nStep 3 — 'python' appears {python_count} time(s) in the essay.")

# Replace "python" with "Python 🐍"
replaced = clean_essay.replace("python", "Python 🐍")
print(f"\nStep 4 — After replacement:\n{replaced}")

# Split into sentences
sentences = clean_essay.split(". ")
print(f"\nStep 5 — List of sentences:\n{sentences}")

# Print sentences numbered, ensuring each ends with a "."
print("\nStep 6 — Numbered sentences:")
for i, sentence in enumerate(sentences, start=1):
    # Check if sentence already ends with "." — if not, add one
    if not sentence.endswith("."):
        sentence = sentence + "."
    print(f"  {i}. {sentence}")